options:
  suite: "Navigator.ba regression suite" #this can be used in a setup where multiple projects share the same test results database 
  build: "0.0.2"
dbconnection:
  adapter: postgresql
  database:  rspec
  username: postgres
  password: password
  host: localhost
  port: 5432
